services:
  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./client
    ports:
      - 3000:80
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend

  web-server:
    container_name: web-server
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/fullchain.pem
      - ./privkey.pem:/etc/nginx/privkey.pem
    ports:
      - 443:443
      - 80:80
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    name: app-network
